apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 1
  template:
    metadata:
      labels:
        app: "goserver"
    spec:
      containers:
      - name: "goserver"
        image: "geraldobl58/hello-go:v5"
        envFrom:
        - configMapRef:
            name: goserver-env

        volumeMounts:
        - mountPath: "/go/cars"
          name: config

      volumes:
      - name: config
        configMap:
          name: configmap-car
          items:
          - key: members
            path: car.txt
