apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 1
  template:
    metadata:
      labels:
        app: "goserver"
    spec:
      containers:
      - name: "goserver"
        image: "geraldobl58/hello-go:v7.1"

        readinessProbe:
          httpGet:
            path: /healthz
            port: 8000
          periodSeconds: 3
          failureThreshold: 1
          initialDelaySeconds: 10

        # livenessProbe:
        #   httpGet:
        #     path: /healthz
        #     port: 8000
        #   periodSeconds: 5
        #   failureThreshold: 3
        #   timeoutSeconds: 1
        #   successThreshold: 1

        envFrom:
        - configMapRef:
            name: goserver-env
        - secretRef:
            name: goserver-secret
        volumeMounts:
        - mountPath: "/go/cars"
          name: config

      volumes:
      - name: config
        configMap:
          name: configmap-car
          items:
          - key: members
            path: car.txt
